services:
  restaurant-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: restaurant_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - restaurant-net

  restaurant-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DSN: postgres://postgres:password123@restaurant-db:5432/restaurant_api?sslmode=disable
      PORT: 3003
    depends_on:
      - restaurant-db
    networks:
      - restaurant-net
    ports:
      - "3003:3003"

volumes:
  pgdata:

networks:
  restaurant-net: