version: "3.8"

services:
  app:
    build:
      context: .
    container_name: restaurant-api
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant_api
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"